use core::mem::offset_of;

use deko_macros::with_atomic_pred;
use deko_std::prelude::*;
use vstd::prelude::*;

use crate::cpu::task::X86ExceptionContext;
use crate::mm::paging::GLOBAL;
use crate::mm::DEKO_FRAME_ALLOCATOR_FULL;
use crate::{kinfo, kpanic_if, kwarn};

core::arch::global_asm!(
    include_str!("idt.S"),
    EXCEP_FLAGS_OFF = const offset_of!(X86ExceptionContext, frame.flags),
    EXCEP_CS_OFF = const offset_of!(X86ExceptionContext, frame.cs),
    EXCEP_RCX_OFF = const offset_of!(X86ExceptionContext, regs.rcx),
    EXCEP_RIP_OFF = const offset_of!(X86ExceptionContext, frame.rip),
    options(att_syntax)
);

// This is auto-generated by `build.rs`.
core::arch::global_asm!(include_str!("idt_gen.S"), options(att_syntax));

verus! {

global layout IdtEntry is size == 16;

extern "C" {
    fn de_handler();
    fn db_handler();
    fn nmi_handler();
    fn bp_handler();
    fn of_handler();
    fn br_handler();
    fn ud_handler();
    fn nm_handler();
    fn df_handler();
    fn ts_handler();
    fn np_handler();
    fn ss_handler();
    fn gp_handler();
    fn pf_handler();
    fn mf_handler();
    fn ac_handler();
    fn mce_handler();
    fn xf_handler();
    fn ve_handler();
    fn cp_handler();
    fn hv_handler();
    fn vc_handler();
    fn sx_handler();
    fn int80_handler();
    fn irq_int_inj_handler();
    fn irq_ipi_handler();
}

func_ptr!(de_handler);
func_ptr!(db_handler);
func_ptr!(nmi_handler);
func_ptr!(bp_handler);
func_ptr!(of_handler);
func_ptr!(br_handler);
func_ptr!(ud_handler);
func_ptr!(nm_handler);
func_ptr!(df_handler);
func_ptr!(ts_handler);
func_ptr!(np_handler);
func_ptr!(ss_handler);
func_ptr!(gp_handler);
func_ptr!(pf_handler);
func_ptr!(mf_handler);
func_ptr!(ac_handler);
func_ptr!(mce_handler);
func_ptr!(xf_handler);
func_ptr!(ve_handler);
func_ptr!(cp_handler);
func_ptr!(hv_handler);
func_ptr!(vc_handler);
func_ptr!(sx_handler);
func_ptr!(int80_handler);
func_ptr!(irq_int_inj_handler);
func_ptr!(irq_ipi_handler);

/// The global interrupt descriptor table (IDT).
///
/// This is defined as a [`DekoOnceCell`] to a pointer because we do not intend to
/// modify the IDT on the stack and want to ensure that it is only initialized once.
pub exec static GLOBAL_IDT: DekoOnceCell<DekoPPtr<Idt>, DekoPointsTo<Idt>, DekoPPtrPred>
    ensures
        GLOBAL_IDT.wf(),
{
    DekoOnceCell::new(Ghost(DekoPPtrPred {  }))
}

/// Loads the global IDT if it is initialized.
pub fn load_global_idt() {
    if let Some(DekoAtomicData {
        data: idt,
        perm: idt_perm,
    }) = GLOBAL_IDT.get() {
        let idt = idt.borrow(Tracked(idt_perm.borrow()));

        idt.load();
    } else {
        kwarn!("Global IDT is not initialized; this is a no-op");
    }
}

/// Initialize the global IDT. This should only be called once.
pub fn init_global_idt() {
    kinfo!("Initializing global IDT");

    kpanic_if!(
        GLOBAL_IDT.get().is_some(),
        "Global IDT is already initialized",
    );

    let (idt_ptr, Tracked(mut idt_perm)) = boxed_ptr!(Idt, &DEKO_FRAME_ALLOCATOR_FULL);

    kinfo!("Populating exception handlers in global IDT");

    Idt::populate_exceptions(idt_ptr, Tracked(&mut idt_perm));

    kinfo!("Global IDT initialized");

    // load this idt.
    idt_ptr.borrow(Tracked(&idt_perm)).load();

    kinfo!("Global IDT loaded");

    // test_pf_handler(); // you can enable this to see this page fault handler has been called.

    GLOBAL_IDT.init(DekoAtomicData::new_with(idt_ptr, Tracked(idt_perm)));
}

#[verifier::external_body]
fn test_pf_handler() {
    let r = unsafe {
        core::ptr::read(0xdeadbeef as *const u8)
    };
}

pub const DE_VECTOR: usize = 0;

pub const DB_VECTOR: usize = 1;

pub const NMI_VECTOR: usize = 2;

pub const BP_VECTOR: usize = 3;

pub const OF_VECTOR: usize = 4;

pub const BR_VECTOR: usize = 5;

pub const UD_VECTOR: usize = 6;

pub const NM_VECTOR: usize = 7;

pub const DF_VECTOR: usize = 8;

pub const CSO_VECTOR: usize = 9;

pub const TS_VECTOR: usize = 10;

pub const NP_VECTOR: usize = 11;

pub const SS_VECTOR: usize = 12;

pub const GP_VECTOR: usize = 13;

pub const PF_VECTOR: usize = 14;

pub const MF_VECTOR: usize = 16;

pub const AC_VECTOR: usize = 17;

pub const MCE_VECTOR: usize = 18;

pub const XF_VECTOR: usize = 19;

pub const VE_VECTOR: usize = 20;

pub const CP_VECTOR: usize = 21;

pub const HV_VECTOR: usize = 28;

pub const VC_VECTOR: usize = 29;

pub const SX_VECTOR: usize = 30;

pub const INT_INJ_VECTOR: usize = 0x50;

pub const IPI_VECTOR: usize = 0xE0;

pub const SYSCALL: usize = 0x80;

const IDT_TARGET_MASK_1: u64 = 0x0000_0000_0000_ffff;

const IDT_TARGET_MASK_2: u64 = 0x0000_0000_ffff_0000;

const IDT_TARGET_MASK_3: u64 = 0xffff_ffff_0000_0000;

const IDT_TARGET_MASK_1_SHIFT: u64 = 0;

const IDT_TARGET_MASK_2_SHIFT: u64 = 48 - 16;

const IDT_TARGET_MASK_3_SHIFT: u64 = 32;

const IDT_TYPE_MASK: u8 = 0x0f;

const IDT_TYPE_SHIFT: u64 = 40;

const IDT_TYPE_CALL: u8 = 0x0c;

const IDT_TYPE_INT: u8 = 0x0e;

const IDT_TYPE_TRAP: u8 = 0x0f;

pub fn create_early_idt() -> (arr: Array<IdtEntry, 256>)
    ensures
        arr.wf(),
        forall|i: int|
            0 <= i && i < 256 ==> #[trigger] arr@[i as int].high == 0 && arr@[i as int].low == 0,
{
    broadcast use deko_std::array::lemma_sized_t_makes_sized_array;

    Array::fill(IdtEntry::no_handler())
}

/// The base addresses of the IDT should be aligned on an 8-byte boundary
/// to maximize performance of cache line fills.
#[repr(C, packed(8))]
#[derive(Copy, Clone)]
pub struct IdtEntry {
    pub low: u64,
    pub high: u64,
}

impl WellFormed for IdtEntry {
    closed spec fn wf(&self) -> bool {
        true
    }
}

impl IdtEntry {
    pub const fn no_handler() -> (r: Self)
        ensures
            r.wf(),
            r.low == 0,
            r.high == 0,
    {
        Self { low: 0, high: 0 }
    }

    fn create(target: VirtAddr, cs: u16, desc_type: u8, dpl: u8, ist: u8) -> Self {
        let vaddr = target.0 as u64;
        let cs_mask = (cs as u64) << IDT_CS_SHIFT;
        let ist_mask = ((ist as u64) & IDT_IST_MASK) << IDT_IST_SHIFT;
        let low = (vaddr & IDT_TARGET_MASK_1) << IDT_TARGET_MASK_1_SHIFT | (vaddr
            & IDT_TARGET_MASK_2) << IDT_TARGET_MASK_2_SHIFT | idt_type_mask(desc_type)
            | IDT_PRESENT_MASK | idt_dpl_mask(dpl) | cs_mask | ist_mask;
        let high = (vaddr & IDT_TARGET_MASK_3) >> IDT_TARGET_MASK_3_SHIFT;

        IdtEntry { low, high }
    }

    #[inline(always)]
    pub fn raw_entry(target: VirtAddr) -> Self
    {
        Self::create(target, 8, IDT_TYPE_INT, 0, 0)
    }
}

fn idt_type_mask(t: u8) -> u64 {
    ((t & IDT_TYPE_MASK) as u64) << IDT_TYPE_SHIFT
}

const IDT_DPL_MASK: u8 = 0x03;

const IDT_DPL_SHIFT: u64 = 45;

fn idt_dpl_mask(dpl: u8) -> u64 {
    ((dpl & IDT_DPL_MASK) as u64) << IDT_DPL_SHIFT
}

const IDT_PRESENT_MASK: u64 = 0x1u64 << 47;

const IDT_CS_SHIFT: u64 = 16;

const IDT_IST_MASK: u64 = 0x7;

const IDT_IST_SHIFT: u64 = 32;

#[repr(C, packed(2))]
#[derive(Default, Clone, Copy)]
struct IdtDesc {
    limit: u16,
    address: VirtAddr,
}

pub struct Idt {
    pub entries: Array<IdtEntry, 256>,
}

with_atomic_pred! {
    Idt,
    (),
    fields: { entries  },
    perm_fields: { },
    data.wf()
}
impl WellFormed for Idt {
    open spec fn wf(&self) -> bool {
        &&& self.entries.wf()
        // This is too strong.
        // &&& forall|i: int|
        //     0 <= i && i < 256 ==> #[trigger] self.entries@[i as int].high != 0
        //         || self.entries@[i as int].low != 0
    }
}

impl View for Idt {
    type V = Seq<IdtEntry>;

    closed spec fn view(&self) -> Self::V {
        self.entries@
    }
}

impl Idt {
    pub fn get_base_and_limit(&self) -> (u64, u16)
        requires
            self.wf(),
    {
        let base = addr_of_ref(&self.entries);
        let limit = core::mem::size_of::<IdtEntry>() * 256 - 1;

        (base as u64, limit as u16)
    }

    /// Populate the exception handlers in the IDT.
    ///
    /// # Note
    ///
    /// Since [`Idt`] must occupy a continuous page and `&'static [IdtHandler]` is not
    /// well supported by Verus yet, we resort to raw pointer manipulating again. However,
    /// this operation is safe as long as we ensure that the permissions are correct.
    #[verifier::external_body]
    pub fn populate_exceptions(ptr: DekoPPtr<Self>, Tracked(idt_perm): Tracked<&mut DekoPointsTo<Self>>)
        requires
            ptr@ == old(idt_perm).pptr(),
            old(idt_perm).wf(),
        ensures
            idt_perm.wf(),
            idt_perm.is_init(),
            idt_perm.pptr() == old(idt_perm).pptr(),
    {
        let this = unsafe {
            &mut *(ptr.addr() as *mut Idt)
        };

        this.entries.update(DE_VECTOR, IdtEntry::raw_entry(VirtAddr::new(de_handler_func_ptr())));
        this.entries.update(DB_VECTOR, IdtEntry::raw_entry(VirtAddr::new(db_handler_func_ptr())));
        this.entries.update(NMI_VECTOR, IdtEntry::raw_entry(VirtAddr::new(nmi_handler_func_ptr())));
        this.entries.update(BP_VECTOR, IdtEntry::raw_entry(VirtAddr::new(bp_handler_func_ptr())));
        this.entries.update(OF_VECTOR, IdtEntry::raw_entry(VirtAddr::new(of_handler_func_ptr())));
        this.entries.update(BR_VECTOR, IdtEntry::raw_entry(VirtAddr::new(br_handler_func_ptr())));
        this.entries.update(UD_VECTOR, IdtEntry::raw_entry(VirtAddr::new(ud_handler_func_ptr())));
        this.entries.update(NM_VECTOR, IdtEntry::raw_entry(VirtAddr::new(nm_handler_func_ptr())));
        this.entries.update(DF_VECTOR, IdtEntry::raw_entry(VirtAddr::new(df_handler_func_ptr())));
        this.entries.update(TS_VECTOR, IdtEntry::raw_entry(VirtAddr::new(ts_handler_func_ptr())));
        this.entries.update(NP_VECTOR, IdtEntry::raw_entry(VirtAddr::new(np_handler_func_ptr())));
        this.entries.update(SS_VECTOR, IdtEntry::raw_entry(VirtAddr::new(ss_handler_func_ptr())));
        this.entries.update(GP_VECTOR, IdtEntry::raw_entry(VirtAddr::new(gp_handler_func_ptr())));
        this.entries.update(PF_VECTOR, IdtEntry::raw_entry(VirtAddr::new(pf_handler_func_ptr())));
        this.entries.update(HV_VECTOR, IdtEntry::raw_entry(VirtAddr::new(hv_handler_func_ptr())));
        this.entries.update(SYSCALL, IdtEntry::raw_entry(VirtAddr::new(int80_handler_func_ptr())));
        this.entries.update(IPI_VECTOR, IdtEntry::raw_entry(VirtAddr::new(irq_ipi_handler_func_ptr())));
        this.entries.update(INT_INJ_VECTOR, IdtEntry::raw_entry(VirtAddr::new(irq_int_inj_handler_func_ptr())));
    }

    /// Load an IDT.
    ///
    /// # Safety
    ///
    /// Since we have no guarantee that the IDT is valid, this function is unsafe.
    /// The caller must ensure that the IDT is valid before calling this function.
    #[verifier::external_body]
    pub fn load(&self)
        requires
            self.wf(),
    {
        let base: *const IdtEntry = self.entries.index(0);
        let limit = core::mem::size_of::<IdtEntry>() * 256 - 1;

        let desc = IdtDesc { limit: limit as u16, address: VirtAddr::from(base) };

        unsafe {
            core::arch::asm!(
                "lidt (%rax)",
                in("rax") &desc,
                options(att_syntax),
            );
        }
    }

    /// Initialize an IDT entry.
    pub fn init(&mut self, addr: *const u8, size: usize)
        requires
            addr as usize + size * 32 <= usize::MAX,
            size <= old(self).entries@.len(),
            old(self).entries.wf(),
        ensures
            forall|i: int| 0 <= i < size as int ==> #[trigger] self.entries@[i as int].wf(),
    {
        let mut i = 0;
        let addr = addr as usize;

        while i < size
            invariant
                0 <= i <= size,
                size <= self.entries@.len(),
                addr + size * 32 <= usize::MAX,
                addr + i * 32 <= usize::MAX,
                old(self).entries@.len() == self.entries@.len(),
                self.entries.wf(),
            decreases size - i,
        {
            let this_addr = VirtAddr::from((addr as usize + i * 32) as u64);

            self.entries.update(i, IdtEntry::raw_entry(this_addr));

            i += 1;
        }
    }

    #[inline(always)]
    pub fn from_idt_entries(entries: Array<IdtEntry, 256>) -> (r: Self)
        requires
            entries.wf(),
            forall|i: int|
                0 <= i && i < 256 ==> #[trigger] entries@[i as int].high != 0
                    || entries@[i as int].low != 0,
        ensures
            r.wf(),
    {
        Idt { entries }
    }
}

/// Initialize the early IDT used in stage2. This will remain in scope as long as
/// stage2 is in memory.
#[verifier::external_body]
#[verus_spec(r =>
    // with Tracked(ctx_perm): Tracked<&crate::cpu::DekoCpuCtxPermission>,
    requires
        old(early_idt).entries. wf(),
    ensures
        early_idt.wf(),
)]
pub fn init_early_idt(early_idt: &mut Idt) {
    unsafe {
        early_idt.init(
            &stage2_generic_idt_handler_no_ghcb as *const u8,
            core::mem::size_of::<IdtEntry>(),
        );
    }

    early_idt.load();
}

#[verifier::external_body]
pub fn init_generic_idt(early_idt: &mut Idt)
    requires
        old(early_idt).wf(),  // since we must have called init_early_idt

    ensures
        early_idt.wf(),
{
    unsafe {
        early_idt.init(&stage2_generic_idt_handler as *const u8, core::mem::size_of::<IdtEntry>());
    }

    early_idt.load();
}

#[verusfmt::skip]
extern "C" {
    pub static stage2_generic_idt_handler_no_ghcb: u8;
    pub static stage2_generic_idt_handler: u8;
}

} // verus!
