[workspace]
resolver = "2"
members = ["deko-core"]

[workspace.dependencies]
# Verus repos
vstd = { git = "https://github.com/hiroki-chen/verus", rev = "b185da5", default-features = false }
builtin = { git = "https://github.com/hiroki-chen/verus", rev = "b185da5" }
builtin_macros = { git = "https://github.com/hiroki-chen/verus", rev = "b185da5" }

syn_verus = { git = "https://github.com/ziqiaozhou/verus", rev = "7c4a5274a4d74522f3965eb038bb7e22fa5eebef", features = [
    "full",
    "visit-mut",
    "extra-traits",
] }
prettyplease_verus = { git = "https://github.com/ziqiaozhou/verus", rev = "7c4a5274a4d74522f3965eb038bb7e22fa5eebef" }

# the profile used for `cargo build`
[profile.dev]
panic = "abort"    # disable stack unwinding on panic
incremental = true

# the profile used for `cargo build --release`
[profile.release]
panic = "abort"    # disable stack unwinding on panic
incremental = true
debug = false
