[workspace]
resolver = "2"
members = [
    "deko-core",
    "deko-logging",
    "deko-macros",
    "deko-playground",
    "deko-stage1",
    "deko-std",
    "xtask",
    "tests/buddy",
    "tests/elf",
    # bins
    "bin/deko-monitor",
    "bin/deko-stage2",
]
exclude = ["tools/verus"]

[workspace.dependencies]
vstd = { git = "https://github.com/verus-lang/verus.git", default-features = false }
verus_builtin = { git = "https://github.com/verus-lang/verus.git" }
verus_builtin_macros = { git = "https://github.com/verus-lang/verus.git" }
verus_state_machines_macros = { git = "https://github.com/verus-lang/verus.git" }

syn_verus = { git = "https://github.com/ziqiaozhou/verus", rev = "7c4a5274a4d74522f3965eb038bb7e22fa5eebef", features = [
    "full",
    "visit-mut",
    "extra-traits",
] }
prettyplease_verus = { git = "https://github.com/ziqiaozhou/verus", rev = "7c4a5274a4d74522f3965eb038bb7e22fa5eebef" }

deko-core = { path = "deko-core", default-features = false }
deko-logging = { path = "deko-logging" }
deko-macros = { path = "deko-macros" }
deko-std = { path = "deko-std" }
elf = { git = "https://github.com/hiroki-chen/elf-rs.git" }

# the profile used for `cargo build`
[profile.dev]
panic = "abort"    # disable stack unwinding on panic
incremental = true

# the profile used for `cargo build --release`
[profile.release]
panic = "abort"    # disable stack unwinding on panic
incremental = true
debug = false
