[workspace]
resolver = "2"
members = [
    "deko-core",
    "deko-logging",
    "deko-macros",
    "deko-stage1",
    "deko-std",
    "xtask",
    # bins
    "bin/deko-monitor",
    "bin/deko-stage2", "bin/init",
]
# Unfortunately due to `Cargo`'s default feature unification, we need to
# exclude some crates that have conflicting default features like global
# allocator API in tests.
exclude = ["tools/verus", "tests/buddy", "tests/collections", "tests/elf", "deko-analysis"]

[workspace.dependencies]
vstd = { git = "https://github.com/hiroki-chen/verus.git", default-features = false, branch = "verus-spec-const-fix" }
verus_builtin = { git = "https://github.com/hiroki-chen/verus.git", branch = "verus-spec-const-fix" }
verus_builtin_macros = { git = "https://github.com/hiroki-chen/verus.git", branch = "verus-spec-const-fix" }
verus_state_machines_macros = { git = "https://github.com/hiroki-chen/verus.git", branch = "verus-spec-const-fix" }

syn_verus = { git = "https://github.com/ziqiaozhou/verus", rev = "7c4a5274a4d74522f3965eb038bb7e22fa5eebef", features = [
    "full",
    "visit-mut",
    "extra-traits",
] }
prettyplease_verus = { git = "https://github.com/ziqiaozhou/verus", rev = "7c4a5274a4d74522f3965eb038bb7e22fa5eebef" }

deko-core = { path = "deko-core", default-features = false }
deko-logging = { path = "deko-logging" }
deko-macros = { path = "deko-macros" }
deko-std = { path = "deko-std", default-features = false }
elf = { git = "https://github.com/hiroki-chen/elf-rs.git" }

# the profile used for `cargo build`
[profile.dev]
panic = "abort"    # disable stack unwinding on panic
incremental = true

# the profile used for `cargo build --release`
[profile.release]
panic = "abort"    # disable stack unwinding on panic
incremental = true
debug = false
