[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
dirs = "6.0.0"
fatfs = "0.3.6"
fscommon = "0.1.1"
git2 = "0.20.2"
igvm = "0.3.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3.1.1"
toml = "0.8.23"
walkdir = "2.5.0"
xshell = "0.2.7"
colored = "2.0"
