[build]
target-dir = "target"
incremental = true

[alias]
xtask = "run --package xtask --release --"

qemu-tdx = "xtask --target-arch tdx qemu --config-path .config/qemu.tdx.config.toml"
qemu-snp = "xtask --target-arch snp qemu --config-path .config/qemu.snp.config.toml"

create-bootable-tdx = "xtask  --target-arch tdx create-bootable --deko-monitor-path target/x86_64-tdx-deko/release/deko-monitor"
create-bootable-snp = "xtask  --target-arch snp create-bootable --deko-monitor-path target/x86_64-sev-deko/release/deko-monitor.bin"

build-deko-tdx-release = "xtask --target-arch tdx build --target deko --release"
build-deko-snp-release = "xtask --target-arch snp build --target deko --release"
build-deko-tdx-debug = "xtask --target-arch tdx build --target deko"
build-deko-snp-debug = "xtask --target-arch snp build --target deko"

pretty = "xtask pretty"

# TODO: Fork another version. This will download unncessary git submodules recursively.
install-igvmbuilder = "install --git https://github.com/coconut-svsm/svsm.git igvmbuilder"
