[build]
target-dir = "target"
incremental = true

[alias]
xtask = "run --package xtask --"

qemu = "xtask qemu"
qemu-debug = "xtask qemu --debug"
create-bootable = "xtask create-bootable"

build-deko-release = "xtask build --target deko --release"
build-deko-debug = "xtask build --target deko"
