[package]
name = "deko-core"
edition = "2021"

[package.metadata.verus]
verify = true

[dependencies]
vstd = { workspace = true, features = ["allow_panic"] }
verus_builtin = { workspace = true }
verus_builtin_macros = { workspace = true }

deko-logging = { workspace = true, optional = true }
deko-macros = { workspace = true }
deko-std = { workspace = true, features = ["alloc"] }
elf = { workspace = true }
paste = "1.0.15"
seq-macro = "0.3.6"
heapless = "0.9.2"
aes-gcm = { version = "0.10.3", default-features = false, features = [
  "aes",
  "arrayvec",
  "zeroize",
] }
sha3 = { version = "0.10.8", default-features = false }
uuid = { version = "1.20.0", default-features = false }
rand_core = { version = "0.10.0", default-features = false }

[build-dependencies]
chrono = { version = "0.4", features = ["std"] }

[features]
default = [
  "snp",
  "logging",
  "alloc",
] # Note that logging should be off for production-ready builds.
alloc = ["deko-std/alloc"]
global_alloc_api = ["alloc"]
tdx = []
snp = ["deko-std/snp"]
# Enable logging?
logging = ["deko-logging", "deko-std/logging"]
