[package]
name = "deko-core"
edition = "2021"

[[bin]]
path = "src/stage2.rs"
name = "stage2"
test = false

[[bin]]
path = "src/monitor.rs"
name = "deko"
test = false

[package.metadata.verus]
verify = true

[dependencies]
vstd = { workspace = true, features = ["allow_panic"] }
verus_builtin = { workspace = true }
verus_builtin_macros = { workspace = true }

deko-logging = { workspace = true, optional = true }
deko-macros = { workspace = true }
deko-std = { workspace = true, features = ["alloc", "global_alloc"] }
elf = { workspace = true }
paste = "1.0.15"

[features]
default = [
  "snp",
  "logging",
] # Note that logging should be off for production-ready builds.
tdx = []
snp = ["deko-std/snp"]
# Enable logging?
logging = ["deko-logging", "deko-std/logging"]
