[package]
name = "deko-std"
version = "0.1.0"
edition = "2021"

[dependencies]
vstd = { workspace = true }
verus_builtin = { workspace = true }
verus_builtin_macros = { workspace = true }
verus_state_machines_macros = { workspace = true }

itoa = { version = "1.0.15", features = ["no-panic"] }
lexical-core = { version = "1.0.6", default-features = false, features = [
  "write-integers",
  "write-floats",
  "power-of-two",
] }
paste = "1.0.15"
ryu = { version = "1.0.20", features = ["no-panic"] }

deko-macros = { workspace = true }

[package.metadata.verus]
verify = true

[features]
default = ["alloc", "snp"]
alloc = ["vstd/alloc"]
global_alloc = ["alloc"]
logging = []
snp = []
tdx = []
