[package]
name = "deko-std"
version = "0.1.0"
edition = "2021"

[dependencies]
vstd = { workspace = true }
builtin = { workspace = true }
builtin_macros = { workspace = true }
state_machines_macros = { workspace = true }
paste = "1.0.15"

[package.metadata.verus]
verify = true

[features]
default = ["alloc"]
snp = []
tdx = []
alloc = ["vstd/alloc"]
