memory = "64G"
debug = false
extra_config = [
  "-cpu",
  "EPYC-v5",
  "-d",
  "int,cpu_reset",
  "-D",
  "qemu.log",
  # Using this disk image for launching the Linux guest.
  "-drive",
  "file=tools/noble-server-cloudimg-amd64.img,format=qcow2,snapshot=off,id=disk0,if=none",
  "-device",
  "virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=on",
  # Disk device
  "-device",
  "scsi-hd,drive=disk0",
  # Network device
  "-netdev",
  "user,id=vmnic,hostfwd=tcp::10022-:22",
  "-device",
  "e1000,netdev=vmnic,romfile=",
  "-serial",
  "mon:stdio",
  "-virtfs",
  "local,path=/home/haobchen/deko-linux,mount_tag=host_share,security_model=none,id=fs0",
  "-kernel",
  "/home/haobchen/deko-linux/arch/x86/boot/bzImage",
  "-append",
  "root=/dev/sda1 console=ttyS0 no5lvl nopti hugepages=0 mem_encrypt=on"
]
# For debugging please reduce cores to catch early logic bugs.
smp_cores = 1
